### ISSUE TITLE
File renaming not working

### ISSUE THREAD

**Issue by collegeitguy** [taggartsoftware/albumdownload#19]
Hello,

When download items from an album, the files are not being renamed. It is converting to jpg properly, but it is saving with the original file name so the ordering is not preserved. 
I'm on Windows 10 using chrome 81.

See attached for screen shot with downloaded file name.

Am I missing an option somewhere?

Thanks,
Nate

![image](https://user-images.githubusercontent.com/65664803/82451257-b82f8b80-9a7b-11ea-8ea7-850554d6d81a.png)

**Comment by ctaggart** [comment]
Hey @collegeitguy, are you on a corporate controlled computer by chance? This was reported once before and the user just had to switch to his personal laptop.

**Comment by ctaggart** [comment]
Leaving #20 open.
