### ISSUE TITLE
File renaming not working

### ISSUE THREAD

**Issue by hhall1** [taggartsoftware/albumdownload#20]
Hi there! 

I have one issue with the application and one suggestion. 

My issue is that the file is not renaming. I've signed in and out of the app, restarted my computer and this just doesn't work for me. I am using Windows 10 and this is a personal computer. Please let me know what I can do to troubleshoot this issue.

Second, my suggestion would be having downloads into zip files instead of individual files. This would be very useful for folders with more than a handful of files. 

Awesome app by the way! I love the concept.

Thank you! 

![ADError](https://user-images.githubusercontent.com/69003196/88935579-e685d000-d24f-11ea-9ad2-a2aa57b8249e.JPG)

**Comment by ctaggart** [comment]
Hi @hhall1, sorry for the delayed response and hat it did not work for you on that computer. Did you try another computer? Did you have any other Chrome extensions installed that might interfere?

**Comment by hhall1** [comment]
Hey,

Sorry! I completely forgot I had reached out about this issue. I did not try another computer, but my accounts sync on all my computers so not sure if that matters. 

Also, I don't know - I have a ton of extensions that I use for work - I needed this for work as well. 

Any recommendations on troubleshooting?

**Comment by ctaggart** [comment]
I recommend troubleshooting by turning off all the other extensions. chrome://extensions
A customer reported this by email in November:

> found a way to fix the issue, it was related to another extension which was installed. In my case it was Nimbus Screenshot tool, I guess also other tools which save images or files and setting a name for them will interfere with your extension.

**Comment by hhall1** [comment]
Awesome! Thank you for that information. I do use the Nimbus extension, so
that's probably it. I will give it a try and if that doesn't work I will
reach back out! Thanks again.
