### ISSUE TITLE
Videoresolution is 1080 (instead of 4k) after download

### ISSUE THREAD

**Issue by TomPez** [taggartsoftware/albumdownload#21]
Hi,

first of all: great and helpfull extension.

The problem I have is that all my videos on google photos are in 4k, but after I download them with your extension they are max 1080 (or smaller videos from google photos like 1080 are then 640x480).

Please note that I am currently in the free trial period.

Greetings from Austria,
Tom

**4k on Google Photos:**

![image](https://user-images.githubusercontent.com/2791577/95220216-83d42600-07f6-11eb-96c6-570787bc5cea.png)

**1080 after download:**

![image](https://user-images.githubusercontent.com/2791577/95220044-538c8780-07f6-11eb-98ee-10c17847eed1.png)

**Comment by TomPez** [comment]
Found out that this is an issue with the Google api: https://issuetracker.google.com/issues/80149160
So its not a bug in your extension.

**Comment by ctaggart** [comment]
Thanks for reporting @TomPez and finding the issue.
