### ISSUE TITLE
When an album is opened it is the usual google photos interface not the one that manages downloads 

### ISSUE THREAD

**Issue by seancull** [taggartsoftware/albumdownload#22]
installed the extension
authenticated
got a list of albums
clicked on an album
album opened in normal google interface not the albumdownload interface shown in YouTube
purchased extension
same issue
see image
![2020-10-12_08-58-39](https://user-images.githubusercontent.com/3306959/95771414-ec1d7e80-0cb2-11eb-837b-205b8c9a5de8.jpg)

**Comment by seancull** [comment]
Thanks for your very prompt response. I got it working, it would also be good if you could download all of the photos without a confirmation click per photo , 600+ photos.

**Comment by ctaggart** [comment]
@seancull, great! The confirmation is a Chrome setting. You can disable it at:
chrome://settings/downloads

<img width="987" alt="image" src="https://user-images.githubusercontent.com/80104/95803805-453edf80-0cbe-11eb-91a5-8f8f2689963a.png">

You need to add this to a FAQ in the docs.
