### ISSUE TITLE
no photos listed for album from Google API

### ISSUE THREAD

**Issue by ctaggart** [taggartsoftware/albumdownload#24]
An album from Robert A Sibley named `Egypt` says it has 890 or so `mediaCount`, but when clicking on the album, no photos show up. The Google Photos API returned `{}` for a GET to `https://photoslibrary.googleapis.com/v1/mediaItems:search?albumId=AMKmXu2frWvX-nNkNYTCc8XhxpNrD46abtvR7yBfr-xG5vmb26sbzd_eQbrTOuhqPasIG3_NNvNr&pageSize=100 `. The HTTP response was 200.

The suggested workaround was to select all the pictures in the album in Google Photos and add them to a  new album named `Egypt 2` or similar.

**Comment by Damien1963** [comment]
?
