### ISSUE TITLE
Chrome Web Store disabled payments on February 1st

### ISSUE THREAD

**Issue by ctaggart** [taggartsoftware/albumdownload#25]
https://developer.chrome.com/docs/webstore/cws-payments-deprecation/

Free trials were disabled on December 1st. All payments will be disabled on February 1st. I am currently investigating how to switch subscriptions over to Stripe or other payments system.

**Comment by ctaggart** [comment]
I have not had time to build out my own payments website.  The extension is still available to be be installed and used by anyone who has already purchased a subscription. New purchases are not allowed since February 1st until I build my own payments website and update the extension to use it. I'll do it, but it is going to take a while. Here are some screenshots.

## "No longer available" for new customers

![image](https://user-images.githubusercontent.com/80104/106808515-55891a80-661f-11eb-8102-bda64211e4e5.png)


## current users can still "Add to Chrome"

![image](https://user-images.githubusercontent.com/80104/106808464-430ee100-661f-11eb-8e2f-4cc6b3968dd1.png)

**Comment by coopseth** [comment]
I would have paid for this, had it been available. Is there a estimated release date for this re-release?

**Comment by ctaggart** [comment]
@coopseth, I'm actively working on Stripe payments integration again. Hopefully, end of August.

**Comment by ctaggart** [comment]
Fixed! You can sign up for a subscription at https://albumdownload.ctaggart.com/.

I just submitted version 2.0.1 for review. If you want it sooner, pay for a subscription and I can send you the extension with instructions for loading it in developer mode at `chrome://extensions`.
![image](https://user-images.githubusercontent.com/80104/125710246-89f2993e-e4ee-49a1-a149-97593b53645b.png)
