### ISSUE TITLE
Where to purchase a subscription?

### ISSUE THREAD

**Issue by Shellywell123** [taggartsoftware/albumdownload#29]
I am trying to find where to purchase a subscription for the 'Album Download Chrome Extension'. So that I can begin using it.
I have looked on every site/link I can find with no luck ( github / webstore / main ).

All I can find is that on the main site it lists Stripe as a payment method in the `2021-07 changelog` with a link back to the home page of the main site.

Please can you help point me in the right direction?

Thanks in advance

**Comment by Shellywell123** [comment]
You have to sign in to get the link. It is at the top of https://albumdownload.ctaggart.com/. 
![unnamed](https://user-images.githubusercontent.com/44142139/126494357-c4b099fc-6446-4c57-abe6-b23b24925519.png)

**Comment by ctaggart** [comment]
It is working, but I'm going to reopen this because it needs to be easier. I'm currently figuring out how to move the Stripe links into the Album Download extension itself. I'll close this when that is working.

**Comment by ctaggart** [comment]
For Album Download 2.1, I'm moving the Stripe links into the application. There will be a "Click here to buy a subscription. It is required to download." after signing in.

![image](https://user-images.githubusercontent.com/80104/126906686-b12ab84d-ad6f-4aa7-ad55-167783fd649e.png)

Clicking the link opens a new window to begin checkout:
![image](https://user-images.githubusercontent.com/80104/126906770-662c2167-082a-4664-803f-b5c91c1a509d.png)

If checkout is successful, it redirects to:
![image](https://user-images.githubusercontent.com/80104/126906851-4a75e651-93d7-4ea8-8163-0d6007e9a5d4.png)

If you then refresh the Album Download page, the warning with be gone:
![image](https://user-images.githubusercontent.com/80104/126906884-c3a370c9-f67f-4fe6-bf92-dd0b8d01ef47.png)

You are able to manage your subscription from this menu item:
![image](https://user-images.githubusercontent.com/80104/126906921-7be2f781-6b81-4df5-a2e6-04c1ac6e5ee6.png)

There, you can cancel your subscription if you wish:
![image](https://user-images.githubusercontent.com/80104/126906967-ccb9c2d3-fd0a-44c3-831b-922a5e16ece1.png)

You can still use it for the entire period, but it will not automatically renew.
![image](https://user-images.githubusercontent.com/80104/126907030-931ffeae-959b-49ed-80b9-8386ddecd0f5.png)

It will show the date that it will be cancelled.
![image](https://user-images.githubusercontent.com/80104/126907063-f0de11a6-95fc-4424-a963-8425c8193f2f.png)

You can click "Renew plan" if you no longer wish for it to cancel.
![image](https://user-images.githubusercontent.com/80104/126907087-7ce673fa-0973-4445-a65f-5dedbfc3f5e5.png)

**Comment by ctaggart** [comment]
Version 2.1 is now live in the Chrome Web Store. #31 updates the docs for how to purchase and manage a subscription.
