### ISSUE TITLE
Extension doesn't work in Vivaldi

### ISSUE THREAD

**Issue by markgitset** [taggartsoftware/albumdownload#43]
When I click the login to Google button in Vivaldi, nothing happens.  Was able to work around the issue by using Chrome, but it would be nice if it worked in other chromium-based browsers.  (Full disclosure: I'm also on Linux, though I don't think that's related--it worked for Chrome in Linux.)

**Comment by ctaggart** [comment]
Thanks for the report @markgitset. I have never heard of https://vivaldi.com/ and will have a look.

The extension for Google Chrome is using its built-in authentication. Is it possible to try the extension built for Microsoft Edge? There is a link at https://albumdownload.ctaggart.com/ . It does authentication differently. Edge is also a chromium-based browser.
